/* Passcode gate.
 *
 * Scope, stated honestly: this is a static page on GitHub Pages, so anyone who
 * opens devtools can read this file and skip the gate. It keeps the dashboard
 * from being readable by someone who simply lands on the URL — that is all it
 * is for, and all it is claimed to be.
 *
 * What actually protects the personal data is separate and stronger: the
 * symptom log lives in localStorage, and the check-in sync credentials are
 * entered in Settings and kept in localStorage too. Neither is ever committed
 * to this public repo, so there is nothing here for a bypasser to read.
 *
 * The passcode itself is not stored — only a PBKDF2-SHA256 verifier over a
 * random salt. Change it with:  node tools/set-passcode.mjs "new passphrase"
 */
window.WD = window.WD || {};

WD.auth = (function () {
    const { $, el } = WD.util;

    // --- generated by tools/set-passcode.mjs — do not hand-edit ---
    const SALT_B64 = 'O+Fyw1rkCPuuTurvtK0pdg==';
    const VERIFY_B64 = 'jA1FDMC5r4OyrIbGqO02XSpwcjBjxihre1wyvre8r9Y=';
    const ITERATIONS = 250000;
    // --- end generated ---

    const COOKIE = 'wd_gate';
    // Ten years. Practically "does not expire" — browsers cap persistence well
    // below this anyway, and a cookie is the right store because it survives
    // the "clear site data for localStorage" case differently than localStorage.
    const MAX_AGE = 10 * 365 * 24 * 60 * 60;

    function readCookie(name) {
        return document.cookie
            .split('; ')
            .map(part => part.split('='))
            .filter(([k]) => k === name)
            .map(([, v]) => decodeURIComponent(v || ''))[0] || null;
    }

    function writeCookie(name, value) {
        const secure = location.protocol === 'https:' ? '; Secure' : '';
        document.cookie = `${name}=${encodeURIComponent(value)}; Max-Age=${MAX_AGE}; Path=/; SameSite=Lax${secure}`;
    }

    function deleteCookie(name) {
        document.cookie = `${name}=; Max-Age=0; Path=/; SameSite=Lax`;
    }

    const toB64 = (buf) => btoa(String.fromCharCode(...new Uint8Array(buf)));

    async function derive(passphrase) {
        const salt = Uint8Array.from(atob(SALT_B64), c => c.charCodeAt(0));
        const key = await crypto.subtle.importKey(
            'raw', new TextEncoder().encode(passphrase), 'PBKDF2', false, ['deriveBits']);
        const bits = await crypto.subtle.deriveBits(
            { name: 'PBKDF2', salt, iterations: ITERATIONS, hash: 'SHA-256' }, key, 256);
        return toB64(bits);
    }

    // Length-independent comparison. Not load-bearing in a client-side gate,
    // but it costs nothing and keeps the habit.
    function constantTimeEqual(a, b) {
        if (typeof a !== 'string' || typeof b !== 'string') return false;
        let diff = a.length ^ b.length;
        for (let i = 0; i < Math.max(a.length, b.length); i++) {
            diff |= (a.charCodeAt(i) || 0) ^ (b.charCodeAt(i) || 0);
        }
        return diff === 0;
    }

    const isUnlocked = () => constantTimeEqual(readCookie(COOKIE) || '', VERIFY_B64);

    function lock() {
        deleteCookie(COOKIE);
        location.reload();
    }

    /* Resolves once the page is unlocked. Callers await this before doing any
     * work, so nothing is fetched or rendered behind the gate. */
    function unlock() {
        return new Promise((resolve) => {
            const overlay = $('#lock-screen');

            if (isUnlocked()) {
                // The class is in the markup so the page never flashes before
                // the gate paints. Clearing it here matters: `locked` carries
                // `overflow: hidden`, so leaving it on made the whole page
                // unscrollable on every visit after the first.
                document.body.classList.remove('locked');
                overlay.remove();
                resolve();
                return;
            }

            document.body.classList.add('locked');
            const form = $('#lock-form');
            const input = $('#lock-input');
            const error = $('#lock-error');
            const submit = $('#lock-submit');

            if (!window.crypto || !crypto.subtle) {
                // WebCrypto needs a secure context. file:// and https:// both
                // qualify; plain http:// on a LAN address does not.
                error.textContent = 'This page must be opened over https (or as a local file) for the passcode to work.';
                error.hidden = false;
                input.disabled = submit.disabled = true;
                return;
            }

            form.addEventListener('submit', async (e) => {
                e.preventDefault();
                const value = input.value.trim();
                if (!value) return;

                submit.disabled = true;
                submit.textContent = 'Checking…';
                error.hidden = true;

                let ok = false;
                try {
                    ok = constantTimeEqual(await derive(value), VERIFY_B64);
                } catch (err) {
                    console.error('Passcode check failed', err);
                }

                if (ok) {
                    writeCookie(COOKIE, VERIFY_B64);
                    overlay.classList.add('unlocking');
                    document.body.classList.remove('locked');
                    setTimeout(() => overlay.remove(), 320);
                    resolve();
                    return;
                }

                submit.disabled = false;
                submit.textContent = 'Unlock';
                error.textContent = 'Not that one.';
                error.hidden = false;
                input.select();
                overlay.querySelector('.lock-card').classList.remove('shake');
                void overlay.offsetWidth; // restart the animation
                overlay.querySelector('.lock-card').classList.add('shake');
            });

            // Autofocus without stealing it from a password manager mid-fill.
            setTimeout(() => input.focus(), 50);
        });
    }

    return { unlock, lock, isUnlocked };
})();
